一覧と詳細実装
YukiYouda/journal_site_app pull request #1
Opened 2021-09-20 05:33 UTC by YukiYouda

よろしくおねがいします。

2021-09-20 06:27 UTC, narusesuzuki reviewed
お疲れさまです！課題1バッチリです！🙆‍♂️
課題2もfeatureブランチで進めて、再度slackで教えて下さい！

2021-09-20 21:06 UTC, kazu-taka approved these changes
@YukiYouda 
マージしてOKです✨
![LGTM](https://image.lgtmoon.dev/133608)

2021-09-21 00:15 UTC, kazu-taka requested changes
@YukiYouda 
1点修正お願いします🙏

2021-09-21 00:15 UTC, kazu-taka commented on resources/views/articles/edit.blade.php
> +        <input type="hidden" name="id" value="{{ $article->id }}">
@YukiYouda 
ルーティングはresourceを使用していたので、idは渡す必要がないので削除してOKです！
削除後動作確認お願いします✨

2021-09-21 00:15 UTC, kazu-taka commented on resources/views/articles/show.blade.php
> +        <input type="submit" value="一覧へ戻る" onclick="history.back()">
@YukiYouda 
一覧画面以外から遷移してきた時(URL直打ち)に、一覧に戻ることができないので修正お願いします!

2021-09-21 00:52 UTC, kazu-taka commented
@YukiYouda 
問題ないのでマージしてOKです！！
![LGTM](https://image.lgtmoon.dev/74586)

2021-09-21 01:04 UTC, merged